name: Java CI with Quality Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Aggiornato alla versione 4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    
    - name: Build and validate
      run: |
        mvn -B clean verify
        mvn jacoco:check
        mvn checkstyle:check
    
    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4  # Versione corretta
      with:
        name: quality-reports
        path: |
          target/site/jacoco/
          target/checkstyle-result.xml